name: scoped
description: simple dependency injection using a root scope inherited widget and a store factory
version: 0.1.2
homepage: http://github.com/agrapine/scoped
authors:
  - Alexandru R. Agrapine <alexandru@agrapine.com>

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
