name: scoped
description: dependency injection with scoped store
version: 0.0.3
homepage: http://github.com/agrapine/scoped
authors:
  - Alexandru R. Agrapine <alexandru@agrapine.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
