name: scoped
description: a pragmatic state management solution. comes with  instance store (single, lazy & and scoped) and handy connectors
version: 1.9.6
homepage: https://github.com/swipelab/scoped

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
