name: scoped
description: a pragmatic state management solution. comes with  instance store (single, lazy & and scoped) and handy connectors
version: 1.9.2
homepage: http://github.com/swipelab/scoped
authors:
  - Alexandru R. Agrapine <alex@swipelab.co>
  - Basile Raynaud <b.c.j.raynaud@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
